version: '3.8'
services:
  db:
    image: postgres:15
    container_name: audiorecords_db
    volumes:
      - db_value:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  audio_converter_app:
    build:
      context: .
    container_name: audio_converter_app 
    env_file:
      - .env
    depends_on:
      - db
    command: ["/audio_converter_app/docker/app.sh"]
    ports:
      - 8000:8000

volumes:
  db_value:
